common: &common
  every_2m:
    class: CronTasksWorker
    cron: '0 1-59/2 * * * * Asia/Kolkata'
    args: []
local:
  <<: *common

staging:
  <<: *common

uat:
  <<: *common

live:
  <<: *common
  every_400AM:
    class: CronTasksWorker
    cron: '0 0 4 * * * Asia/Kolkata'
    args: []
  